/**
 * Response bank for the barge-in demo.
 *
 * These responses are intentionally long-winded and self-aware about the
 * barge-in behaviour — the point of the demo is for the user to interrupt
 * mid-stream, so the agent invites them to try and explains what happens
 * under the hood once they do.
 */

export const bargeInResponses: string[] = [
  "Here is the thing about barge-in. Right now I am going to keep talking. I am going to keep generating tokens for a long time, and you can sit there and read along, or you can do what this demo actually exists to show you: interrupt me. Type a new message while I am mid-sentence and hit enter. Watch what happens. The response you are reading will stop immediately, get marked as interrupted in the UI, and your new message will start a fresh turn. No waiting for the first response to finish. No wasted tokens on content you no longer want. That is what barge-in means in a production AI application — the ability to change your mind and have the system respect that change instantly, the same way a human conversation lets you interrupt someone without being impolite.",

  "Let me explain what barge-in actually costs you when you do not have it. In a plain HTTP streaming setup, the LLM keeps generating tokens until it hits its stop condition. If you change your mind mid-stream, your only options are to close the connection (which wastes whatever the model already generated and leaves your server in an awkward state) or to buffer the response and discard it client-side (which still costs you the tokens on the provider's bill). Neither is a clean story. The demo you are currently inside shows a different approach: the cancel signal flows through the Ably channel to the server, the server's AbortSignal fires, the LLM stream stops at the source, and the encoder publishes a final message marking this response as aborted. That final message includes the partial content so the UI has a complete record of what was said before the interruption. Try it — interrupt me right now. Type a new message. I will stop, you will see the interrupted marker, and the next turn will start without ceremony.",

  "The pattern here is deliberately designed for real user behaviour. People change their minds. They start asking a question, realise halfway through that they should be asking a different question, and want to pivot. In a text chat with another human that is trivial — the other person just stops reading the old message and reads the new one. But with a streaming AI, every token costs money, every token takes time, and the naive implementation forces the user to wait for a response they no longer care about before sending the new one. Barge-in fixes that. You can interrupt me right now by typing and hitting enter. The cancel propagates through Ably, the server-side abort signal fires, my token generation stops, and the response gets marked with an aborted status that the client renders as interrupted. Your next message is a brand new turn, not a continuation of this one, so the LLM sees a clean conversation state. Try it.",

  "Something important about this demo that is easy to miss: the interrupted response does not disappear. It stays in the conversation history with whatever content made it through before cancellation, marked with an interrupted indicator so it is clear to both the user and any downstream system that this response was cut short. That matters because some applications want to remember what was partially said — for audit, for context continuity, for debugging. The AIT protocol publishes an abort status on the final message of the stream, and the conversation tree holds onto everything up to that point. When you start a new turn by sending a new message, the server sees the full history including the interrupted response and can factor it into the next reply if it wants to. Go ahead and interrupt me now. Type a new message and hit enter. Watch the interrupted marker appear, then watch the new response stream in cleanly.",

  "Think about the voice-assistant case. Someone says 'Hey, what is the weather in London', the assistant starts speaking, and halfway through they say 'Actually, make that Paris'. The assistant needs to stop talking immediately and switch. That is barge-in, and it is one of the hard problems in conversational AI because the full stack has to cooperate — the audio pipeline has to stop playing, the LLM has to stop generating, the session has to remember what happened. AI Transport gives you the session layer for this. The cancel signal flows on the same channel as the tokens, ordering is preserved, and the response tree records the interruption so the next turn has full context. Try it right now. Type something, anything, while I am still streaming. You will see this response stop and your new one take over.",
];
