name: npm release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: cli-release-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: "write"
      id-token: "write"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
        with:
          submodules: true
      - name: Set up pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
        with:
          version: 10 # Use pnpm version 10
      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: "22.x" # Use Node.js 22.x
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies and publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
          pnpm publish --provenance --access public --no-git-checks
